# enum for HTTP response codes
from enum import Enum


class HTTPStatus(Enum):
    OK = 200
    NOT_FOUND = 404
    INTERNAL_SERVER_ERROR = 500
    BAD_REQUEST = 400
    UNAUTHORIZED = 401
    FORBIDDEN = 403
    METHOD_NOT_ALLOWED = 405
    CONFLICT = 409
    TOO_MANY_REQUESTS = 429
    SERVICE_UNAVAILABLE = 503
    GATEWAY_TIMEOUT = 504
    UNPROCESSABLE_ENTITY = 422
